### ISSUE TITLE
Get docker file working and write a README file :)

### ISSUE THREAD

**Issue by FrankenSteinxD** [mhd999/azure-notifcation#1]
for now the docker config is not working, and there's no readme file to explain how to get this code working even without docker.

**Comment by mhd999** [comment]
will add the steps needed to run the app on docker and locally

**Comment by mhd999** [comment]
Fix the docker image is this PR [2](https://github.com/mhd999/azure-notifcation/pull/2) (don't forget to replace the the vars in the docker file with your own vars).

Also added the instruction needed to setup and runt he app to the readme file [3](https://github.com/mhd999/azure-notifcation/pull/3).
